server:
  port: 8080
spring:
  application:
    name: ServiceA
  cloud:
    sentinel:
      filter:
        enabled: false
      web-context-unify: false
      transport:
        port: 8719
        dashboard: 192.168.5.66:8088
      log:
        dir: ./logs.csp



logging:
  config: classpath:${LOGBACK_FILE:logback-local.xml}