server:
  port: 8080
spring:
  application:
    name: ServiceA
  cloud:
    sentinel:
      filter:
        enabled: false
      web-context-unify: false
      transport:
        port: 8719
        dashboard: 192.168.5.66:8088
      log:
        dir: ./logs.csp
      datasource:
        # 名称随意
        flow:
          nacos:
            server-addr: 192.168.5.66:8848
            namespace: 414e212fc38c41e8aecc45f31f624002
            dataId: sentinel-flow
            groupId: SENTINEL
            rule-type: flow


logging:
  config: classpath:${LOGBACK_FILE:logback-local.xml}